import type { AppSettings, VoiceProfile } from "../types";
import { DEFAULT_GEMINI_MODEL } from "../lib/gemini";

export const defaultSettings: AppSettings = {
  id: 1,
  cleanupIntervalMinutes: 5,
  encryptionEnabled: false,
  geminiModel: DEFAULT_GEMINI_MODEL,
  conversationFontScale: 1,
};

export const defaultVoiceProfiles: VoiceProfile[] = [
  {
    name: "Jenny Neural",
    locale: "en-US",
    style: "general",
    rate: 1,
    pitch: 0,
    tags: ["default"],
    isDefault: true,
    azureVoiceId: "en-US-JennyNeural",
  },
  {
    name: "Xiaoxiao (zh-CN)",
    locale: "zh-CN",
    style: "general",
    rate: 1,
    pitch: 0,
    tags: ["mandarin"],
    azureVoiceId: "zh-CN-XiaoxiaoNeural",
  },
  {
    name: "HsiaoChen (zh-TW)",
    locale: "zh-TW",
    style: "general",
    rate: 1,
    pitch: 0,
    tags: ["taiwanese"],
    azureVoiceId: "zh-TW-HsiaoChenNeural",
  },
  {
    name: "YunJhe (zh-TW)",
    locale: "zh-TW",
    style: "general",
    rate: 1,
    pitch: 0,
    tags: ["taiwanese"],
    azureVoiceId: "zh-TW-YunJheNeural",
  },
  {
    name: "HsiaoYu (zh-TW, Female)",
    locale: "zh-TW",
    style: "general",
    rate: 1,
    pitch: 0,
    tags: ["taiwanese", "female"],
    azureVoiceId: "zh-TW-HsiaoYuNeural",
  },
  {
    name: "Cora (en-US Multilingual)",
    locale: "en-US",
    style: "general",
    rate: 1,
    pitch: 0,
    tags: ["multilingual"],
    azureVoiceId: "en-US-CoraMultilingualNeural",
  },
  {
    name: "Davis (en-US Multilingual)",
    locale: "en-US",
    style: "general",
    rate: 1,
    pitch: 0,
    tags: ["multilingual"],
    azureVoiceId: "en-US-DavisMultilingualNeural",
  },
  {
    name: "Derek (en-US Multilingual)",
    locale: "en-US",
    style: "general",
    rate: 1,
    pitch: 0,
    tags: ["multilingual"],
    azureVoiceId: "en-US-DerekMultilingualNeural",
  },
  {
    name: "Dustin (en-US Multilingual)",
    locale: "en-US",
    style: "general",
    rate: 1,
    pitch: 0,
    tags: ["multilingual"],
    azureVoiceId: "en-US-DustinMultilingualNeural",
  },
  {
    name: "Emma (en-US Multilingual)",
    locale: "en-US",
    style: "general",
    rate: 1,
    pitch: 0,
    tags: ["multilingual"],
    azureVoiceId: "en-US-EmmaMultilingualNeural",
  },
  {
    name: "Evelyn (en-US Multilingual)",
    locale: "en-US",
    style: "general",
    rate: 1,
    pitch: 0,
    tags: ["multilingual"],
    azureVoiceId: "en-US-EvelynMultilingualNeural",
  },
  {
    name: "Lewis (en-US Multilingual)",
    locale: "en-US",
    style: "general",
    rate: 1,
    pitch: 0,
    tags: ["multilingual"],
    azureVoiceId: "en-US-LewisMultilingualNeural",
  },
  {
    name: "Lola (en-US Multilingual)",
    locale: "en-US",
    style: "general",
    rate: 1,
    pitch: 0,
    tags: ["multilingual"],
    azureVoiceId: "en-US-LolaMultilingualNeural",
  },
  {
    name: "Nancy (en-US Multilingual)",
    locale: "en-US",
    style: "general",
    rate: 1,
    pitch: 0,
    tags: ["multilingual"],
    azureVoiceId: "en-US-NancyMultilingualNeural",
  },
];
